config/routes.rb
Rails.application.routes.draw do
  
  devise_for :managers
  
  root 'users#index'

  devise_for :users
  
  
  resources :users #do
  
  resources :responds do 
        collection do
          get :responded_issue
          get :unresponded_issue
        end
  end
  
  resources :items , :except => [:show] do
    member do
      get :multi
      post :multi_save
    end
  end
  
  resources :issues, :only => [:show]
  

  namespace :dashboard do
    resources :users do
      resources :issues
      resources :options
      resources :profiles 
      resources :responds do 
        collection do
          get   :responded_issue
          get   :unresponded_issue
          get   :special_cates
          post  :special_cates_save
        end
      end
    end
    namespace :admin do 
      resources :users
      resources :managers
      resources :cates
      resources :ordinary_cates
      resources :special_cates
      resources :issues
      resources :options
     end
   end

  

  

end

app/models/respond.rb
class Respond < ActiveRecord::Base
    belongs_to :user
    belongs_to :option
    #accepts_nested_attributes_for :option
    
    
end

app/controllers/dashboard/responds_controller.rb
class  Dashboard::RespondsController < Dashboard::DashboardController 
   
    before_action :find_respond, only: [:show, :edit, :update, :destroy]
    
    
    
    def index
        #回答過的問題
        @responded_issue      = @user.respond.all
        #@responded_issue      = Respond.where(id: @user.respond.map{|t| t.id}
        #未答過的問題
        @unresponded_issue  = Issue.where.not(id: @user.issue.map{|t| t.id} )
    end
    
    def responded_issue
        @responded_issue      = current_user.respond.all.order('updated_at DESC')
    end
    
    def unresponded_issue
        @unresponded_issue  = Issue.where.not(id: @user.issue.map{|t| t.id})
    end
    
    def special_cates
        @respond = @user.respond.new
        @special_cates = SpecialCate.find_by(:id => 4)
        @issues = @special_cates.issue
        
    end
    
   
    
    def new
        @respond = @user.respond.build
    	@issue = Issue.find(params[:q])
    end
    
    
    def edit
       
        @respond = Respond.find(params[:id])
    end
    
    def create 
       @respond = @user.respond.new(respond_params)
       if @respond.save
           redirect_to unresponded_issue_dashboard_user_responds_path
       else
           render :new
       end
    end
    
    def update
        if @respond.update(respond_params)
            redirect_to responded_issue_dashboard_user_responds_path
        else
           render :edit
        end
    end
    
    
    
    
    private
    
    
    def respond_params
        params.require(:respond).permit(:user_id, :option_id)
    end
    
    def find_respond
        @respond = Respond.find(params[:id])
    end
    
end

app/controllers/responds_controller.rb
class  RespondsController < ApplicationController
   
    before_action :find_respond, only: [:show, :edit, :update, :destroy]
    before_action :find_user
    
    
    
    def index
        #回答過的問題
        @responded_issue      = @user.respond.all
        #@responded_issue      = Respond.where(id: @user.respond.map{|t| t.id}
        #未答過的問題
        @unresponded_issue  = Issue.where.not(id: @user.issue.map{|t| t.id} )
    end
    
    def responded_issue
        @responded_issue      = current_user.respond.all.order('updated_at DESC')
    end
    
    def unresponded_issue
        @unresponded_issue  = Issue.where.not(id: @user.issue.map{|t| t.id})
    end
    
   
    
   
    
    
    
    private
    
    def find_user
        @user = current_user
    end
    
    
    def respond_params
        params.require(:respond).permit(:user_id, :option_id)
    end
    
    def find_respond
        @respond = Respond.find(params[:id])
    end
    
end

app/helpers/responds_helper.rb
module RespondsHelper
end

app/views/responds/index.html.erb
<style>

.table > tbody > tr > td {
    padding: 8px;
    line-height: 1.428571429;
    vertical-align: middle;
    border-top: 1px solid #ddd;
}
.issue_title{
  width: 100%;
  /* margin: 0 auto; */
  text-align: left;
  /* padding-left: 20px; */
  color: rgb(121, 95, 153);
  /* background-color: #B09CC6; */
  padding-top: 20px;
  padding-bottom: 0px;
  border-radius: 3px;
}



.issue_wrapper{
  max-width: 935px;
  min-height: 950px;
  /*border: 1px solid #dbdbdb;*/
  border-radius: 3px;
  width: 100%;
  height: 100%;
	display: block;
  /*background-color: #FFF;*/
	padding: 10px;
	text-align: center;
	margin: 20px auto;
}

.title_text {
  display: inline-block;
  width: 126px;
  border-bottom: 3px solid #B09CC6;
  text-align: center;
}

.title_content{
    width: 140px;
    margin: 0 auto;
}




.table_design{
  text-align: left;
}

.table_wrapper{
 padding: 10px; 
}

.table-borderless tbody tr td, .table-borderless tbody tr th, .table-borderless thead tr th {
    border: none;
    text-align: left;
}

</style>

<div class='issue_wrapper'>
  <ul class='issue_title'>
    <li class='title_text'>
      <h4>已回答過的問題</h4>
      </li>
  </ul>
  <div class='content_wrapper'> 
  <div class='table_wrapper'>
    <table class='table table-hover table-borderless table_design'>
    <thead>
      <tr>
        <th class="col-md-1"></th>
        <th class="col-md-6" ></th>
        <th class="col-md-3"></th>
        <th class="col-md-1"></th>
        <th class="col-md-1"></th>
        <th class="col-md-1"></th>
      </tr>
    </thead>
    <tbody>
     <% if @responded_issue %>
        <% @responded_issue.each do |ri| %>
        <tr>
          <td><%= label_tag ri.option.issue.id %></td>
          <td><%= label_tag ri.option.issue.content %></td>
          <td><%= label_tag ri.option.content %></td>
          <td><%= label_tag ri.updated_at.strftime('%x') %> </td>
          <td><%= link_to "改答案", edit_dashboard_user_respond_path(@user, ri.id), class:"btn btn-purple" %></td>
          <td><%= link_to "誰答過？", issue_path(ri.option.issue.id), class:"btn btn-purple" %></td>
        </tr>
      <% end %>
      <% end %>
    </tbody>
    </table>
  </div>
</div>
</div>

<div class='issue_wrapper'>
  <ul class='issue_title'>
    <li class='title_text'>
      <h4>未回答過的問題</h4>
      </li>
  </ul>
  <div class='content_wrapper'> 
  <div class='table_wrapper'>
    <table class='table table-hover table-borderless'>
    <thead>
      <tr>
        <th class="col-md-2">Issue ID</th>
        <th class="col-md-6" >Issue Content</th>
        <th class="col-md-2">修改</th>
      </tr>
    </thead>
    <tbody>
       <% @unresponded_issue.each do |nri| %>
        <tr>
          <td><%= label_tag nri.id %></td>
          <td><%= label_tag nri.content %></td>
          <td><%= link_to "回答", new_dashboard_user_respond_path(@user,:q => nri.id),class:"btn btn-purple" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/responds/responded_issue.html.erb
<style>

.table > tbody > tr > td {
    padding: 8px;
    line-height: 1.428571429;
    vertical-align: middle;
    border-top: 1px solid #ddd;
}
.issue_title{
  width: 100%;
  /* margin: 0 auto; */
  text-align: left;
  /* padding-left: 20px; */
  color: rgb(121, 95, 153);
  /* background-color: #B09CC6; */
  padding-top: 20px;
  padding-bottom: 0px;
  border-radius: 3px;
}



.issue_wrapper{
  max-width: 935px;
  min-height: 950px;
  /*border: 1px solid #dbdbdb;*/
  border-radius: 3px;
  width: 100%;
  height: 100%;
	display: block;
  /*background-color: #FFF;*/
	padding: 10px;
	text-align: center;
	margin: 20px auto;
}

.title_text {
  display: inline-block;
  width: 126px;
  border-bottom: 3px solid #B09CC6;
  text-align: center;
}

.title_content{
    width: 140px;
    margin: 0 auto;
}




.table_design{
  text-align: left;
}

.table_wrapper{
 padding: 10px; 
}

.table-borderless tbody tr td, .table-borderless tbody tr th, .table-borderless thead tr th {
    border: none;
    text-align: left;
}

</style>

<div class='issue_wrapper'>
  <ul class='issue_title'>
    <li class='title_text'>
      <h4>已回答過的問題</h4>
      </li>
  </ul>
  <div class='content_wrapper'> 
  <div class='table_wrapper'>
    <table class='table table-hover table-borderless table_design'>
    <thead>
      <tr>
        <th class="col-md-1"></th>
        <th class="col-md-6" ></th>
        <th class="col-md-3"></th>
        <th class="col-md-1"></th>
        <th class="col-md-1"></th>
        <th class="col-md-1"></th>
      </tr>
    </thead>
    <tbody>
     <% if @responded_issue %>
        <% @responded_issue.each do |ri| %>
        <tr>
          <td><%= label_tag ri.option.issue.id %></td>
          <td><%= label_tag ri.option.issue.content %> </td>
          <td><%= label_tag ri.option.content %> </td>
          <td><%= label_tag ri.updated_at.strftime('%x') %> </td>
          <td><%= link_to "改答案", edit_dashboard_user_respond_path(@user, ri.id), class:"btn btn-purple" %></td>
          <td><%= link_to "#{ri.option.issue.user.count-1}人回答", issue_path(ri.option.issue.id), class:"btn btn-purple" %></td>
        </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>
</div>

app/views/responds/unresponded_issue.html.erb
<style>

.table > tbody > tr > td {
    padding: 8px;
    line-height: 1.428571429;
    vertical-align: middle;
    border-top: 1px solid #ddd;
}
.issue_title{
  width: 100%;
  /* margin: 0 auto; */
  text-align: left;
  /* padding-left: 20px; */
  color: rgb(121, 95, 153);
  /* background-color: #B09CC6; */
  padding-top: 20px;
  padding-bottom: 0px;
  border-radius: 3px;
}



.issue_wrapper{
  max-width: 935px;
  min-height: 950px;
  /*border: 1px solid #dbdbdb;*/
  border-radius: 3px;
  width: 100%;
  height: 100%;
	display: block;
  /*background-color: #FFF;*/
	padding: 10px;
	text-align: center;
	margin: 20px auto;
}

.title_text {
  display: inline-block;
  width: 126px;
  border-bottom: 3px solid #B09CC6;
  text-align: center;
}






.table_design{
  text-align: left;
}

.table_wrapper{
 padding: 10px; 
}

.table-borderless tbody tr td, .table-borderless tbody tr th, .table-borderless thead tr th {
    border: none;
    text-align: left;
}

</style>

<div class='issue_wrapper'>
  <ul class='issue_title'>
    <li class='title_text'>
      <h4>未回答過的問題</h4>
      </li>
  </ul>
  <div class='content_wrapper'> 
  <div class='table_wrapper'>
    <table class='table table-hover table-borderless'>
    <thead>
      <tr>
        <th class="col-md-1"></th>
        <th class="col-md-10" ></th>
        <th class="col-md-1"></th>
      </tr>
    </thead>
    <tbody>
      <% @unresponded_issue.each do |nri| %>
        <tr>
          <td><%= label_tag nri.id %></td>
          <td><%= label_tag nri.content %></td>
          <td><%= link_to "回答", new_dashboard_user_respond_path(@user,:q => nri.id),class:"btn btn-purple" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>
</div>