config/routes.rb
Rails.application.routes.draw do
  
  devise_for :managers
  
  root 'users#index'

  devise_for :users
  
  
  resources :users #do
  
  resources :responds do 
        collection do
          get :responded_issue
          get :unresponded_issue
        end
  end
  
  resources :items , :except => [:show] do
    member do
      get :multi
      post :multi_save
    end
  end
  
  resources :issues, :only => [:show]
  

  namespace :dashboard do
    resources :users do
      resources :issues
      resources :options
      resources :profiles 
      resources :responds do 
        collection do
          get   :responded_issue
          get   :unresponded_issue
          get   :special_cates
          post  :special_cates_save
        end
      end
    end
    namespace :admin do 
      resources :users
      resources :managers
      resources :cates
      resources :ordinary_cates
      resources :special_cates
      resources :issues
      resources :options
     end
   end

  

  

end

app/models/answersheet.rb
class Answersheet < ActiveRecord::Base
belongs_to :user
has_many :qa_sheet
has_many :question, through: :qa_sheet
has_many :answer,   through: :qa_sheet
#accepts_nested_attributes_for :questions

end

app/models/questionnaire.rb
class Questionnaire < ActiveRecord::Base
  has_many :questionnaire_survey
  has_many :survey, through: :questionnaire_survey
  #accepts_nested_attributes_for :questionnaire_surveys
  #has_many :questions, :through => :surveys
  #accepts_nested_attributes_for :surveys, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

end

app/controllers/answersheets_controller.rb
class AnswersheetsController < ApplicationController
	

    before_action :find_user, only: [:show, :new, :edit, :create,:update] 
    before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy] 
 


	def show
		@answersheet = @user.answersheet
	end

	def new
        
        @answersheet = @user.build_answersheet
		#@answersheet = Answersheet.find(params[:user_id])
		@question = Question.all

	end
	 
	def edit
        
        
	end

	def create
		@answersheet = @user.build_answersheet(answersheet_params)
		if @answersheet.save
          redirect_to user_path(@user)
        else
          render :new
        end
	end

	def update
	   @answersheet = @user.answersheet

	   if @answersheet.update(answersheet_params)
	     redirect_to user_path(@user), notice: "文章修改成功！"
	   else
	     render :edit
	  end
	end

	def destroy
	end
private
    
    def answersheet_params
      params.require(:answersheet).permit(:title, :answer_ids =>[])
    end

    private

  def find_user
      @user = User.find(params[:user_id])
  end  

end

app/controllers/dashboard/answersheets_controller.rb
class  Dashboard::AnswersheetsController < Dashboard::DashboardController 

    before_action :find_user, only: [:show, :new, :edit, :create,:update] 
    before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy] 
 

   


	def show
		@answersheet = @user.answersheet
		@question = Question.all
	end

	def new        
    @answersheet = @user.build_answersheet(:user_id => current_user.id)
		@question = Question.all
  end

	 
	def edit
       
	end

	def create

		@answersheet = @user.build_answersheet(answersheet_params)
		if @answersheet.save
			redirect_to dashboard_user_answersheet_path(@user, @answersheet)
		else
			render :new
		end
	end

	def update
	   @answersheet = Answersheet.find(params[:id])

	   if @answersheet.update(answersheet_params)
	     redirect_to dashboard_user_answersheet_path, notice: "文章修改成功！"
	   else
	     render :edit
	  end
	end

	def destroy
	end

    def multi
	    
	   
	    @qasheet = QaSheet.where(:answersheet_id => current_user.answersheet.id)
	    @question = Question.all

	end
	  
	def multi_save


	    #取出所有關連id
	    ids = (params[:as_old] || {}).keys.map{|i|i.to_i}

	    #語意：排除送出的id之外的所有隸屬item的都刪除
	    QaSheet.where("answersheet_id = #{current_user.answersheet.id} AND id NOT IN (#{ids.join(',')})").delete_all

	    #更新舊的資料
	    if params[:as_old]
	      params[:as_old].each_pair do |id , data|
	        ic = QaSheet.where(:answersheet_id => current_user.answersheet.id , :id => id).first
	        if ic
	          #這邊要過 permit 或是一個一個指定都行
	          ic.update_attributes(:answer_id => data[:id])
	        end
	      end
	    end

	    #額外新增的都再塞入
	    if params[:as_new]
	      params[:as_new][:answer_ids].each_index do |index|
	        QaSheet.create(:answersheet_id => current_user.answersheet.id , :answer_ids => params[:as_new][:answer_ids][index])
	      end
	    end
	    redirect_to users_path
	end
    
    
   
   private
    
    def answersheet_params
      params.require(:answersheet).permit(:user_id, :title, :answer_ids =>[])
    end

    

    def find_user
      @user = User.find(params[:user_id])
    end 

    

end

app/helpers/answersheets_helper.rb
module AnswersheetsHelper
end

app/views/answersheets/edit.html.erb
 <h1>變更</h1>

 


<%= simple_form_for [@user, @answersheet] do |f| %>
  



  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
    <div>
    <table>
    <thead>
      <tr>
        <td>#</td>
        <td>Questions ID</td>
        <td>Questions</td>
        <td>Answers</td>
      </tr>
    </thead>

          <tbody>
        <%= hidden_field_tag 'answersheet[answer_ids][]','' %>
        <% @question.each do |question| %> 

        <tr>
        <td>#</td>
            <td><%= label_tag question.id %></td>
            <td><%= label_tag question.content %></td>
        <% question.answer.each do |answer| %> 
           <td> <%= check_box_tag "answersheet[answer_ids][]", answer.id, @answersheet.answer.include?(answer) %>
            <%#= check_box_tag "questionnaire[survey_ids][]", survey.id, @questionnaire.survey.include?(survey) %>
            <%= label_tag answer.content %></td>
      <% end %>
      <% end %>
</tr>
    <tbody>

    </div>
  </p>
   
   <div class="actions">
    <%= f.submit %>
   </div>
<% end %>   

app/views/answersheets/index.html.erb
<div>
  <div>
    <%= link_to("回答更多問題", new_user_answersheet_path) %>
  </div>
  <table>
    <thead>
      <tr>
        <td>#</td>
        <td>Answersheets</td>
        <td>Questions</td>
        <td>Answers</td>
      </tr>
    </thead>
    <tbody>
      <% @answersheet.each do |as| %>
      
        <tr>
          <td>#</td>
          <td><%= as.title %></td>
          <% as.answer.each do |a| %>
          <td><%= a.question_id %></td><td><%= a.content %></td>
        </tr>
        
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/answersheets/new.html.erb
  <h1>答題</h1>

 


<%= simple_form_for [@user, @answersheet] do |f| %>
  



  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
    <div>
        <%= hidden_field_tag 'answersheet[answer_ids][]','' %>
        <% @question.each do |question| %> 
            <%= label_tag question.content %>
        <% question.answer.each do |answer| %> 
            <%= check_box_tag "answersheet[answer_ids][]", answer.id %>
            <%= label_tag answer.content %>
      <% end %>
      <% end %>



    </div>
  </p>
   
   <div class="actions">
    <%= f.submit %>
   </div>
<% end %>   

app/views/answersheets/show.html.erb
<div>
  
  <table class="table">
    <thead>
      <tr>
        <td>#</td>
        <td>Questions ID</td>
        <td>Questions</td>
        <td>Answers</td>
      </tr>
    </thead>

          <tbody>
            <% @answersheet.answer.each do |as| %>
            
              <tr>
                <td>#</td>
                <td><%= as.question.id %></td>
                <td><%= as.question.content %></td>
                
                <td><%= as.content %></td>
              </tr>
              
           
            <% end %>
          </tbody>


    
  </table>
</div>


 