config/routes.rb
Rails.application.routes.draw do
  
  devise_for :managers
  
  root 'users#index'

  devise_for :users
  
  
  resources :users #do
  
  resources :responds do 
        collection do
          get :responded_issue
          get :unresponded_issue
        end
  end
  
  resources :items , :except => [:show] do
    member do
      get :multi
      post :multi_save
    end
  end
  
  resources :issues, :only => [:show]
  

  namespace :dashboard do
    resources :users do
      resources :issues
      resources :options
      resources :profiles 
      resources :responds do 
        collection do
          get   :responded_issue
          get   :unresponded_issue
          get   :special_cates
          post  :special_cates_save
        end
      end
    end
    namespace :admin do 
      resources :users
      resources :managers
      resources :cates
      resources :ordinary_cates
      resources :special_cates
      resources :issues
      resources :options
     end
   end

  

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question

    
    has_many :answersheet, through: :qa_sheet

end

app/models/answersheet.rb
class Answersheet < ActiveRecord::Base
belongs_to :user
has_many :qa_sheet
has_many :question, through: :qa_sheet
has_many :answer,   through: :qa_sheet
#accepts_nested_attributes_for :questions

end

app/models/cate.rb
class Cate < ActiveRecord::Base
  has_many :cate_issue
  has_many :issue, through: :cate_issue
  
  #has_many :issue#, :dependent => :destroy
end

app/models/cate_issue.rb
class CateIssue < ActiveRecord::Base
  belongs_to :ordinary_cate
  belongs_to :special_cate
  belongs_to :cate
  belongs_to :issue
end

app/models/issue.rb
class Issue < ActiveRecord::Base
    has_many :cate_issue
    has_many :cate,             through: :cate_issue
    has_many :ordinary_cate,    through: :cate_issue
    has_many :special_cate,     through: :cate_issue
    
    
    #belongs_to :cate
    has_many :option, :dependent => :destroy
    has_many :respond, through: :option
    has_many :user, through: :respond
    
    accepts_nested_attributes_for :option, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
    
    
     #<% cities_array = City.all.map { |city| [city.name, city.id] } %>
  #<%= options_for_select(cities_array) %>
  
  GENDER_TYPES = [ "Male", "Female", "Do not wish to say" ]
  
  CATES_ARRAY = Cate.all.collect {|p| [ p.name, p.id ] }
  ORDINARY_CATES_ARRAY = OrdinaryCate.all.collect {|p| [ p.name, p.id ] }
  SPECIAL_CATES_ARRAY = SpecialCate.all.collect {|p| [ p.name, p.id ] }
  
  #cates_array = Cate.all.collect {|p| [ p.name, p.id ] }
  #ordinarycates_array = OrdinaryCate.all.collect {|p| [ p.name, p.id ] }
  #specialcates_array = SpecialCate.all.collect {|p| [ p.name, p.id ] }
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable#, :registerable,
         #:recoverable, :rememberable, :trackable, :validatable
end

app/models/model.rb
class Model < ActiveRecord::Base
end

app/models/option.rb
class Option < ActiveRecord::Base
    belongs_to :issue
    has_many :respond,  :dependent => :destroy
    has_many :user,     through: :respond
    
    #可以用的
    has_many :profile_option
    has_many :profile,  through: :profile_option
    #可以用的
end

app/models/ordinary_cate.rb
class OrdinaryCate < ActiveRecord::Base
  has_many :cate_issue
  has_many :issue, through: :cate_issue
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
 
  #可以用的
  has_many :profile_option, dependent: :destroy
  has_many :option, through: :profile_option, dependent: :destroy
  accepts_nested_attributes_for :profile_option
  #可以用的
  
  
  self.primary_key = 'user_id'
  GENDER_TYPES = [ "Male", "Female", "Do not wish to say" ]
  
  #validates_presence_of :location
  #validates_presence_of :gender

end

app/models/profile_option.rb
class ProfileOption < ActiveRecord::Base
  belongs_to :profile
  belongs_to :option
  
end

app/models/qa_sheet.rb
class QaSheet < ActiveRecord::Base
	belongs_to :answersheet
	belongs_to :answer
	belongs_to :question

end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :survey
	has_many :answer, :dependent => :destroy
	accepts_nested_attributes_for :answer, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

    
    has_many :answersheet, through: :qa_sheet

end

app/models/questionnaire.rb
class Questionnaire < ActiveRecord::Base
  has_many :questionnaire_survey
  has_many :survey, through: :questionnaire_survey
  #accepts_nested_attributes_for :questionnaire_surveys
  #has_many :questions, :through => :surveys
  #accepts_nested_attributes_for :surveys, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

end

app/models/respond.rb
class Respond < ActiveRecord::Base
    belongs_to :user
    belongs_to :option
    #accepts_nested_attributes_for :option
    
    
end

app/models/special_cate.rb
class SpecialCate < ActiveRecord::Base
  has_many :cate_issue
  has_many :issue, through: :cate_issue
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :question, :dependent => :destroy
  accepts_nested_attributes_for :question, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
  
  has_many :questionnaire_survey
  has_many :questionnaire, through: :questionnaire_survey
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :answersheet

  has_attached_file :avatar, 
     :styles => { :medium => "300x300>", :thumb => "100x100#", :icon => "50X50#" }, 
     :default_url => "/images/:style/missing.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

#name_scope :without_user, lambda{|user| user ? {:conditions => ["id != ?", user.id]} :{} }
scope :all_except, ->(user) { where.not(id: user) }


   has_many :respond#, inverse_of: :user
   #accepts_nested_attributes_for :respond
   has_many :option, through: :respond
   has_many :issue, through: :option
   
   has_one :profile
end

app/controllers/dashboard/admin/issues_controller.rb
class Dashboard::Admin:: IssuesController < Dashboard::Admin::AdminController 
    def index
        @issues = Issue.all
    end
    
    def new
        @issue = Issue.new
        4.times { @issue.option.build }
    end
    
    
    def edit
        @issue = Issue.find(params[:id])
    end
    
    def create
        @issue = Issue.new(issue_params)
        if @issue.save
            redirect_to dashboard_admin_issues_path
        else
            render :new
        end
    end
    
    def update
        @issue = Issue.find(params[:id])
        if @issue.update(issue_params)
            redirect_to dashboard_admin_issues_path
        else
            render :edit
        end
    end
    
    def destroy 
        @issue = Issue.find(params[:id])
        @issue.destroy
        redirect_to dashboard_admin_issues_path
        
    end
    
    private
    def issue_params
        params.require(:issue).permit(:content, :cate_ids => [], :ordinary_cate_ids => [], :special_cate_ids => [], option_attributes:[:issue_id, :id, :content,:_destroy])
    end
    
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
    def show
        @issue = Issue.find(params[:id])
        #@user = @issue.user 
        @user = @paginate = @issue.user.all_except(current_user).paginate(:page => params[:page], :per_page => 12)
    end
    
end

app/helpers/cates_helper.rb
module CatesHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def match_percentage(current_user, user)
    other_user_option = user.option
    number_other_user_option =  other_user_option.length.to_f
    
    current_user_option = current_user.option
    number_current_user_option =  current_user_option.length.to_f
    
    number_same_option = (other_user_option&current_user_option).length.to_f
    
    var_match_current = (number_same_option)/(number_current_user_option)
    var_match_other   = (number_same_option)/(number_other_user_option)
    
    
    @match = number_to_percentage(Math.sqrt(var_match_current * var_match_other)*100, precision: 0)
      
    @match
     

  end
 
 
  def current_user_respond(user_respond,current_user)
  
    @current_user_respond = current_user.issue.find(user_respond.option.issue.id).respond.find_by(:user_id => current_user).option.content
  
    @current_user_respond
  end
end

app/views/dashboard/admin/issues/edit.html.erb
<style>



.option_first_banner{
  width: 100%;
  height: 100%;
}
.clearfix:after {
  visibility: hidden; 
	display: block; 
	font-size: 0;
	content:' '; 
	clear: both;
	height: 0px;
}

.option_right_banner {
    width: 50%; 
    /* height: 100%; */
    position: relative;
    /* float: left;*/
    /* background-color: rgba(0, 0, 0, 0.42); */
    margin-left: 10px;
    margin-top: 100px;
    display: inline-block;
}


.option_content{
  width:100%;
  padding-top: 15px;
  text-align: left;
}

.form-control{
    padding:0px !important;
}

</style>
<div class='content_wrapper option_wrapper'> 
	<ul class = 'option_first_banner clearfix'>
		<li class = 'option_right_banner'>
			<%= form_for @issue, :url => dashboard_admin_issue_path, :method => :PATCH do |f| %>
				<div class="edit_panel panel panel-default">
					<div class="edit_heading panel-heading">
						<h3 class="panel-title">
							編輯問題
						</h3>
          </div>
          <div class="panel-body">
          	<div class='option_content'>
          		<div class="form-group">
          			<%= label_tag "類別：" %> <%= f.select :cate_ids, Cate.all.collect {|p| [ p.name, p.id ] }, { }, {:class =>"form-control", :multiple => true} %>
              </div>
              <div class="form-group">
          			<%= label_tag "一般類別：" %> <%= f.select :ordinary_cate_ids, OrdinaryCate.all.collect {|p| [ p.name, p.id ] }, { }, {:class =>"form-control", :multiple => true} %>
              </div>
              <div class="form-group">
          			<%= label_tag "特殊類別：" %> <%= f.select :special_cate_ids, SpecialCate.all.collect {|p| [ p.name, p.id ] }, { }, {:class =>"form-control", :multiple => true} %>
              </div>
              <div class="form-group">
								<%= label_tag "題目：" %> <%= f.text_field :content, class:"form-control" %>
							</div>
							<div class="form-inline">
								<div class="form-group">
									<%= f.fields_for :option do |option| %>
										<p>
										<%= label_tag "選項：" %>
										<%= option.text_field :content, class:"form-control" %>
										<%= option.check_box :_destroy, class:"checkbox" %><%= label_tag "刪除" %>
										<%#= option.link_to_remove "Remove this Answer" %>
										</p>
									<% end %>
								</div>
							</div>   
            </div>
            <div class="form-group">
                <%= f.submit "送出", class: "btn btn-primary" %>
            </div>
           </div>
          </div>
        <% end %>
    </li>
	</ul>
</div>

 
 
 

app/views/dashboard/admin/issues/index.html.erb
<style>

.table > tbody > tr > td {
    padding: 8px;
    line-height: 1.428571429;
    vertical-align: middle;
    border-top: 1px solid #ddd;
}
.issue_title{
  width: 100%;
  /* margin: 0 auto; */
  text-align: left;
  /* padding-left: 20px; */
  color: rgb(121, 95, 153);
  /* background-color: #B09CC6; */
  padding-top: 20px;
  padding-bottom: 0px;
  border-radius: 3px;
}

.issue_wrapper{
  max-width: 935px;
  min-height: 950px;
  /*border: 1px solid #dbdbdb;*/
  border-radius: 3px;
  width: 100%;
  height: 100%;
	display: block;
  /*background-color: #FFF;*/
	padding: 10px;
	text-align: center;
	margin: 20px auto;
}

.title_text {
  display: inline-block;
  width: 126px;
  border-bottom: 3px solid #B09CC6;
  text-align: center;
}

.title_new {
  display: inline-block;
  margin: 0 0 0 20px;
}

.title-content{
    width: 140px;
    margin: 0 auto;
}




.table_design{
  text-align: left;
}

.table_wrapper{
 padding: 10px; 
}

.table-borderless tbody tr td, .table-borderless tbody tr th, .table-borderless thead tr th {
    border: none;
    text-align: left;
}
</style>

<div class='issue_wrapper'>
  <ul class='issue_title'>
    <li class='title_text'>
      <h4>問題集</h4>
    </li>
    <li class='title_new'>  
      <%= link_to "建新問題", new_dashboard_admin_issue_path, class:"btn btn-primary" %>
    </li>
  </ul>
  <div class='content_wrapper'> 
  <div class='table_wrapper'>
  <table class='table table-hover table-borderless table_design'>
    <thead>
      <tr>
        <th class="col-md-2">Issue ID</th>
        <th class="col-md-6">Issue Content</th>
        <th class="col-md-4">Issue Cate Name</th>
        <th class="col-md-2">修改</th>
      </tr>
    </thead>
    <tbody>
      <% @issues.each do |issue| %>
        <tr>
          <td> <%= issue.id %></td>
          <td> <%= issue.content %></td>
          <td> <%= issue.cate.name %></td>
          <td> <%= link_to "修改", edit_dashboard_admin_issue_path(issue), class:"btn btn-purple" %></td>
          <td> <%= link_to "刪除", dashboard_admin_issue_path(issue), class:"btn btn-purple", method: :delete %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>
</div>

app/views/dashboard/admin/issues/new.html.erb
<style>



.option_first_banner{
  width: 100%;
  height: 100%;
}
.clearfix:after {
  visibility: hidden; 
	display: block; 
	font-size: 0;
	content:' '; 
	clear: both;
	height: 0px;
}

.option_right_banner {
    width: 50%; 
    /* height: 100%; */
    position: relative;
    /* float: left;*/
    /* background-color: rgba(0, 0, 0, 0.42); */
    margin-left: 10px;
    margin-top: 100px;
    display: inline-block;
}


.option_content{
  width:100%;
  padding-top: 15px;
  text-align: left;
}

.form-control{
    padding:0px !important;
}

</style>
<div class='content_wrapper option_wrapper'> 
	<ul class = 'option_first_banner clearfix'>
		<li class = 'option_right_banner'>
			<%= form_for @issue, :url => dashboard_admin_issues_path, :method => :POST do |f| %>
				<div class="edit_panel panel panel-default">
					<div class="edit_heading panel-heading">
						<h3 class="panel-title">
							建新問題
						</h3>
          </div>
          <div class="panel-body">
          	<div class='option_content'>
              <div class="form-group">
                <%#CATES_ARRAY = Cate.all.collect {|p| [ p.name, p.id ] }
  ORDINARY_CATES_ARRAY = OrdinaryCate.all.collect {|p| [ p.name, p.id ] }
  SPECIAL_CATES_ARRAY = SpecialCate.all.collect {|p| [ p.name, p.id ] }%>
          			<%= label_tag "類別：" %> <%= f.select :cate_ids, Issue::CATES_ARRAY, { }, {:class =>"form-control", :multiple => true} %>
              </div>
              <div class="form-group">
          			<%= label_tag "一般類別：" %> <%= f.select :ordinary_cate_ids, Issue::ORDINARY_CATES_ARRAY, { }, {:class =>"form-control", :multiple => true} %>
              </div>
              <div class="form-group">
          			<%= label_tag "特殊類別：" %> <%= f.select :special_cate_ids,  Issue::SPECIAL_CATES_ARRAY, { include_blank: true }, {:class =>"form-control", :multiple => true} %>
              </div>
              <div class="form-group">
								<%= label_tag "題目：" %> <%= f.text_field :content, class:"form-control" %>
							</div>
							<div class="form-inline">
								<div class="form-group">
									<%= f.fields_for :option do |option| %>
										<p>
										<%= label_tag "選項：" %>
										<%= option.text_field :content, class:"form-control" %>
										<%= option.check_box :_destroy, class:"checkbox" %><%= label_tag "刪除" %>
										<%#= option.link_to_remove "Remove this Answer" %>
										</p>
									<% end %>
								</div>
							</div>   
            </div>
            <div class="form-group">
                <%= f.submit "送出", class: "btn btn-primary" %>
            </div>
           </div>
          </div>
        <% end %>
    </li>
	</ul>
</div>

 
 
 
 

app/views/issues/show.html.erb
<style>

ul.items , ul.items li{
    width: 75%;
    list-style: none;
    padding: 0;
    margin: 0 auto;
}

ul.items li{
  margin: 5px auto;
  border-radius: 5px;
  border: 1px solid #e1e8ed;
  border-bottom: 1px solid rgba(121, 95, 153, 0.5);
  border-top: 1px solid #e1e8ed;
  box-shadow: 1px 1px 3px #e1e8ed;
  display: inline-block;
  width: 100%;
  text-align: left;
  /*padding: 30px 30px 10px 30px;*/
}

.index_content{
  display: block;
  height: 100px;
  padding: 25px 0px 0px 30px;
}

.index_thumb{
  margin-right: 10px;
  display: inline-block;
  float: left;
}

.index_user{
  display: block;
  /*float: left;*/
  padding: 10px;
  /*height: 100px;*/
}

ul.items li img{
  display: block;
  max-width: 100%;
	height: auto;
  border-radius: 100%;
  margin-right: 10px;
  display: inline-block;
  height: auto;
}




.last_issue{
  display: block;
  
}





.footer_match{
  border-top: 1px solid #CCC;
  display: block;
  padding-bottom: 5px;
  padding-top: 15px;
  padding-left: 30px;
  margin-top: 10px;
  /* color: #000; */
  border-bottom-right-radius: 5px;
  border-bottom-left-radius: 5px;
  background-color: rgba(239, 239, 239, 0.5);
  text-align: left;
}

.index_name{
  text-align: center;
  width: 100px;
  display: inline-block;
  margin-bottom: 5px;
  font-size: 15px;
  color: #7A609A;
  margin-right: 10px;
}

.match_percentage{
  display: inline-block;
  margin-right: 5px;
  
}

ul.items li a {
  display: inline-block;
  background: transparent;
  border-radius: 3px;
  color:#7A609A;
  text-decoration: none;
}

div ul li a:hover {
    color:#644F7E;
    background-color: transparent;
    text-decoration: none;
}

.issue_title{
  width: 100%;
  /* margin: 0 auto; */
  text-align: left;
  /* padding-left: 20px; */
  color: rgb(121, 95, 153);
  /* background-color: #B09CC6; */
  padding-top: 20px;
  padding-bottom: 0px;
  border-radius: 3px;
}



.issue_wrapper{
  max-width: 935px;
  min-height: 950px;
  /*border: 1px solid #dbdbdb;*/
  border-radius: 3px;
  width: 100%;
  height: 100%;
	display: block;
  /*background-color: #FFF;*/
	padding: 10px;
	text-align: center;
	margin: 20px auto;
}

.title_text {
  display: inline-block;
  width: 126px;
  border-bottom: 3px solid #B09CC6;
  text-align: center;
}
    
.heart{
  color: rgba(255,0,0,0.6);
}

.this_respond {
  display:block;
  font-size: 16px;
  color: #8C6FB1;
  margin-bottom: 5px;
}
              
.lastest_issue {
  display:block;
}

</style>


<div class='issue_wrapper'>
  <ul class='issue_title'>
    <li class='title_text'>
      <h4><%=  @issue.content %></h4>
      </li>
  </ul>
<div class='content_wrapper'>
  <div class="pagination">
    <%= will_paginate @paginate, :page_links => false if @paginate %>
  </div>
  <div>
  <% if current_user %>
    <ul class='items clearfix'>
      <% @user.each do |user| %>
      <li>
        <span class='index_content'>
        <span class='index_thumb'>
          <%= image_tag(user.avatar.url(:thumb)) %>
        </span>
        <span class='index_user'>
            <span class='this_respond'>
              <strong><%= this_respond(@issue, user) %></strong>
            </span> 
            <span class='lastest_issue'>
                最新問題：<%= user.respond.last.option.issue.content %>
            </span>  
        </span>
        </span>
        <span class='footer_match'>
          <span > 
           <strong><%= link_to user.name, user_path(user), class:'index_name'%></strong> 
          </span>
          <span class='match_percentage'>
          <% if user.respond.any? %>
             <span class='heart'><span class='glyphicon glyphicon-heart'></span> <strong><%= match_percentage(current_user, user) %></strong></span>
          <% else %>
            <span class='heart'><span class='glyphicon glyphicon-heart'></span>  <strong>0%</strong></span>
          <% end %>
          </span>
        </span>
      </li>  
      <% end %>
    </ul>
  <% else %>
    <ul class='items'>
    <% @user.each do |user| %>
      <li>
        <%= image_tag(user.avatar.url(:icon)) %>
        <span class='name'> <%= user.name %></span>
      </li>  
    <% end %>
    </ul>
  <% end %>
</div>
 <%= will_paginate @paginate, :page_links => false if @paginate %>
 </div>
 </div>