config/routes.rb
Rails.application.routes.draw do
  
  devise_for :managers
  
  root 'users#index'

  devise_for :users
  
  
  resources :users #do
  
  resources :responds do 
        collection do
          get :responded_issue
          get :unresponded_issue
        end
  end
  
  resources :items , :except => [:show] do
    member do
      get :multi
      post :multi_save
    end
  end
  
  resources :issues, :only => [:show]
  

  namespace :dashboard do
    resources :users do
      resources :issues
      resources :options
      resources :profiles 
      resources :responds do 
        collection do
          get   :responded_issue
          get   :unresponded_issue
          get   :special_cates
          post  :special_cates_save
        end
      end
    end
    namespace :admin do 
      resources :users
      resources :managers
      resources :cates
      resources :ordinary_cates
      resources :special_cates
      resources :issues
      resources :options
     end
   end

  

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question

    
    has_many :answersheet, through: :qa_sheet

end

app/models/answersheet.rb
class Answersheet < ActiveRecord::Base
belongs_to :user
has_many :qa_sheet
has_many :question, through: :qa_sheet
has_many :answer,   through: :qa_sheet
#accepts_nested_attributes_for :questions

end

app/models/cate.rb
class Cate < ActiveRecord::Base
  has_many :cate_issue
  has_many :issue, through: :cate_issue
  
  #has_many :issue#, :dependent => :destroy
end

app/models/cate_issue.rb
class CateIssue < ActiveRecord::Base
  belongs_to :ordinary_cate
  belongs_to :special_cate
  belongs_to :cate
  belongs_to :issue
end

app/models/issue.rb
class Issue < ActiveRecord::Base
    has_many :cate_issue
    has_many :cate,             through: :cate_issue
    has_many :ordinary_cate,    through: :cate_issue
    has_many :special_cate,     through: :cate_issue
    
    
    #belongs_to :cate
    has_many :option, :dependent => :destroy
    has_many :respond, through: :option
    has_many :user, through: :respond
    
    accepts_nested_attributes_for :option, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
    
    
     #<% cities_array = City.all.map { |city| [city.name, city.id] } %>
  #<%= options_for_select(cities_array) %>
  
  GENDER_TYPES = [ "Male", "Female", "Do not wish to say" ]
  
  CATES_ARRAY = Cate.all.collect {|p| [ p.name, p.id ] }
  ORDINARY_CATES_ARRAY = OrdinaryCate.all.collect {|p| [ p.name, p.id ] }
  SPECIAL_CATES_ARRAY = SpecialCate.all.collect {|p| [ p.name, p.id ] }
  
  #cates_array = Cate.all.collect {|p| [ p.name, p.id ] }
  #ordinarycates_array = OrdinaryCate.all.collect {|p| [ p.name, p.id ] }
  #specialcates_array = SpecialCate.all.collect {|p| [ p.name, p.id ] }
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable#, :registerable,
         #:recoverable, :rememberable, :trackable, :validatable
end

app/models/model.rb
class Model < ActiveRecord::Base
end

app/models/option.rb
class Option < ActiveRecord::Base
    belongs_to :issue
    has_many :respond,  :dependent => :destroy
    has_many :user,     through: :respond
    
    #可以用的
    has_many :profile_option
    has_many :profile,  through: :profile_option
    #可以用的
end

app/models/ordinary_cate.rb
class OrdinaryCate < ActiveRecord::Base
  has_many :cate_issue
  has_many :issue, through: :cate_issue
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
 
  #可以用的
  has_many :profile_option, dependent: :destroy
  has_many :option, through: :profile_option, dependent: :destroy
  accepts_nested_attributes_for :profile_option
  #可以用的
  
  
  self.primary_key = 'user_id'
  GENDER_TYPES = [ "Male", "Female", "Do not wish to say" ]
  
  #validates_presence_of :location
  #validates_presence_of :gender

end

app/models/qa_sheet.rb
class QaSheet < ActiveRecord::Base
	belongs_to :answersheet
	belongs_to :answer
	belongs_to :question

end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :survey
	has_many :answer, :dependent => :destroy
	accepts_nested_attributes_for :answer, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

    
    has_many :answersheet, through: :qa_sheet

end

app/models/questionnaire.rb
class Questionnaire < ActiveRecord::Base
  has_many :questionnaire_survey
  has_many :survey, through: :questionnaire_survey
  #accepts_nested_attributes_for :questionnaire_surveys
  #has_many :questions, :through => :surveys
  #accepts_nested_attributes_for :surveys, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

end

app/models/respond.rb
class Respond < ActiveRecord::Base
    belongs_to :user
    belongs_to :option
    #accepts_nested_attributes_for :option
    
    
end

app/models/special_cate.rb
class SpecialCate < ActiveRecord::Base
  has_many :cate_issue
  has_many :issue, through: :cate_issue
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :question, :dependent => :destroy
  accepts_nested_attributes_for :question, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
  
  has_many :questionnaire_survey
  has_many :questionnaire, through: :questionnaire_survey
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :answersheet

  has_attached_file :avatar, 
     :styles => { :medium => "300x300>", :thumb => "100x100#", :icon => "50X50#" }, 
     :default_url => "/images/:style/missing.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

#name_scope :without_user, lambda{|user| user ? {:conditions => ["id != ?", user.id]} :{} }
scope :all_except, ->(user) { where.not(id: user) }


   has_many :respond#, inverse_of: :user
   #accepts_nested_attributes_for :respond
   has_many :option, through: :respond
   has_many :issue, through: :option
   
   has_one :profile
end

app/helpers/cates_helper.rb
module CatesHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def match_percentage(current_user, user)
    other_user_option = user.option
    number_other_user_option =  other_user_option.length.to_f
    
    current_user_option = current_user.option
    number_current_user_option =  current_user_option.length.to_f
    
    number_same_option = (other_user_option&current_user_option).length.to_f
    
    var_match_current = (number_same_option)/(number_current_user_option)
    var_match_other   = (number_same_option)/(number_other_user_option)
    
    
    @match = number_to_percentage(Math.sqrt(var_match_current * var_match_other)*100, precision: 0)
      
    @match
     

  end
 
 
  def current_user_respond(user_respond,current_user)
  
    @current_user_respond = current_user.issue.find(user_respond.option.issue.id).respond.find_by(:user_id => current_user).option.content
  
    @current_user_respond
  end
end

app/views/common/_footer.html.erb
<footer class="footer">
  <small>
    Copyright ©2016 Qupid Design by <a href="http://qupidservice.wix.com/goqupid" target=_new>Sean</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><%= link_to "New",   '#' %></li>
    </ul>
  </nav>
</footer>

app/views/common/_managernavbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a href="/" style='background-color: transparent;'>
          <div id = 'logo'></div>
        </a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_manager %>
        
        
         <li> <%= link_to("登入", new_manager_session_path) %> </li>
       <% else %>
         <li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             Hi!, <%= current_manager.email %>
             <b class="caret"></b>
           </a>
          <ul class="dropdown-menu">
             <li> <%= link_to( "管理員主頁", dashboard_admin_managers_path ) %> </li>
             <li> <%= link_to( "首頁", root_path ) %> </li>
             <li> <%= link_to( "登出", destroy_manager_session_path, method: :delete) %> </li>
           </ul>
         </li>
       <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
        <a href="/" style='background-color: transparent;'>
          <div id = 'logo'></div>
        </a>
    </div>
    
    <div class="collapse navbar-collapse">
       <ul class="nav navbar-nav navbar-left">
        <% if current_user %>
           
          <li class="dropdown">
            <a href="/" class="dropdown-toggle" data-toggle="dropdown">
               <span> 用心，找對人</span> <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
            </a>
            <ul class="dropdown-menu">
              <li> <%= link_to( "最速配", dashboard_user_path(current_user) ) %> </li>
              <li> <%= link_to( "價值觀速配", root_path ) %> </li>
              <li> <%= link_to( "地區速配", edit_user_registration_path )%></li>
              <li> <%= link_to( "興趣速配", destroy_user_session_path, method: :delete) %> </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="/" class="dropdown-toggle" data-toggle="dropdown">
              <span>為愛闖關</span> <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
            </a>
            <ul class="dropdown-menu">
              <li> <%= link_to( "新問題", unresponded_issue_responds_path ) %> </li>
              <li> <%= link_to( "已答題", responded_issue_responds_path ) %> </li>
              <li> <%= link_to( "今日問題", edit_user_registration_path )%></li>
              <li> <%= link_to( "時事題", destroy_user_session_path, method: :delete) %> </li>
            </ul>
          </li>
          
        <% end %>
      </ul>
   
      <ul class="nav navbar-nav navbar-right">
      
        <% if !current_user %>
          <li> <%= link_to("註冊", new_user_registration_path) %> </li>

          <li> <%= link_to("登入", new_user_session_path) %> </li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi!, <%= current_user.name %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li> <%= link_to( "個人頁面", dashboard_user_path(current_user) ) %> </li>
              <li> <%= link_to( "首頁", root_path ) %> </li>
              <li> <%= link_to( "帳號設定", edit_user_registration_path )%></li>
              <li> <%= link_to( "登出", destroy_user_session_path, method: :delete) %> </li>
            </ul>
          </li>
      <% end %>
      
      </ul>
    </div>
  
  </div>
</nav>